DROP PROCEDURE IF EXISTS VerifyInvalidFDVouchers;
CREATE PROCEDURE VerifyInvalidFDVouchers ()
BEGIN
  DECLARE DBName Varchar(50);
  DECLARE RecordsCount Long DEFAULT 0;
  SELECT Database() INTO DBName;

  -- 1. If ClosedFD's FD_VOUCHER_ID is deleted (STATUS=0) in Voucher Master Then
  -- Delete it's FD_INTEREST_VOUCHER_ID in Voucher Master too and Delete Closed FD entry.
  SELECT COUNT(*) INTO RecordsCount  FROM FD_RENEWAL WHERE FD_TYPE='WD'
        AND FD_VOUCHER_ID IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE STATUS = 0);
  IF RecordsCount > 0 THEN
    BEGIN
      UPDATE VOUCHER_MASTER_TRANS AS VM, (SELECT FD_INTEREST_VOUCHER_ID
      FROM FD_RENEWAL WHERE FD_TYPE='WD' AND FD_VOUCHER_ID IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE STATUS = 0)) AS InValidFD
      SET VM.STATUS = 0 WHERE VM.VOUCHER_ID = InValidFD.FD_INTEREST_VOUCHER_ID;

      DELETE FROM FD_RENEWAL WHERE FD_TYPE='WD' AND FD_VOUCHER_ID IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE STATUS = 0);

      SELECT ('1. Verified Closed FD') AS MSG;
    END;
  END IF;

  -- 2. If ClosedFD's FD_VOUCHER_ID =0 or FD_VOUCHER_ID is not avilable in Voucher_Master_Trans
  -- Delete it's FD_INTEREST_VOUCHER_ID in Voucher Master too and Delete Closed FD entry.
  SELECT COUNT(*) INTO RecordsCount  FROM FD_RENEWAL WHERE FD_TYPE='WD' AND FD_VOUCHER_ID NOT IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE VOUCHER_SUB_TYPE='FD');
  IF RecordsCount > 0 THEN
    BEGIN
      UPDATE VOUCHER_MASTER_TRANS AS VM, (SELECT FD_INTEREST_VOUCHER_ID
      FROM FD_RENEWAL WHERE FD_TYPE='WD' AND FD_VOUCHER_ID NOT IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE VOUCHER_SUB_TYPE='FD')) AS InValidFD
      SET VM.STATUS = 0 WHERE VM.VOUCHER_ID = InValidFD.FD_INTEREST_VOUCHER_ID;

      DELETE FROM FD_RENEWAL WHERE FD_TYPE='WD' AND FD_VOUCHER_ID NOT IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE VOUCHER_SUB_TYPE='FD');

      SELECT ('2. Verified Closed FD') AS MSG;
    END;
  END IF;


  -- 3. If ClosedFD's FD_INTEREST_VOUCHER_ID is deleted (STATUS=0) in Voucher Master Then
  -- Null Interest Amount and null FD_INTEREST_VOUCHER_ID in FD Closed Enty
  SELECT COUNT(*) INTO RecordsCount FROM FD_RENEWAL WHERE FD_TYPE='WD' AND FD_INTEREST_VOUCHER_ID > 0
  AND FD_INTEREST_VOUCHER_ID IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE STATUS = 0);
  IF RecordsCount > 0 THEN
    BEGIN
      UPDATE FD_RENEWAL SET INTEREST_AMOUNT=0, FD_INTEREST_VOUCHER_ID=0 WHERE FD_TYPE='WD' AND FD_INTEREST_VOUCHER_ID > 0
      AND FD_INTEREST_VOUCHER_ID IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE STATUS = 0);

      SELECT ('3. Verified Closed FD') AS MSG;
    END;
  END IF;

  -- 4. If ClosedFD's FD_INTEREST_VOUCHER_ID is not exists in Voucher_Master_Trans
  -- Null Interest Amount and null FD_INTEREST_VOUCHER_ID in FD Closed Enty
  SELECT COUNT(*) INTO RecordsCount FROM FD_RENEWAL WHERE FD_TYPE='WD' AND FD_INTEREST_VOUCHER_ID > 0
  AND FD_INTEREST_VOUCHER_ID NOT IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE VOUCHER_SUB_TYPE='FD');
  IF RecordsCount > 0 THEN
    BEGIN
      UPDATE FD_RENEWAL SET INTEREST_AMOUNT=0, FD_INTEREST_VOUCHER_ID=0 WHERE FD_TYPE='WD' AND FD_INTEREST_VOUCHER_ID > 0
      AND FD_INTEREST_VOUCHER_ID NOT IN (SELECT VOUCHER_ID FROM VOUCHER_MASTER_TRANS WHERE VOUCHER_SUB_TYPE='FD');

      SELECT ('4. Verified Closed FD') AS MSG;
    END;
  END IF;

  -- 5. Delete (STATUS=0) FD Contra Voucher entries in Voucher_Master_Trans those are not linked in FD_ACCOUNT and FD_RENEWAL
  SELECT COUNT(*) INTO RecordsCount FROM VOUCHER_MASTER_TRANS WHERE VOUCHER_SUB_TYPE = 'FD' AND VOUCHER_TYPE='CN' AND STATUS = 1
  AND VOUCHER_ID NOT IN ( SELECT FD_VOUCHER_ID FROM FD_RENEWAL UNION ALL SELECT FD_VOUCHER_ID FROM FD_ACCOUNT);
  IF RecordsCount > 0 THEN
    BEGIN
      UPDATE VOUCHER_MASTER_TRANS SET STATUS = 0 WHERE VOUCHER_SUB_TYPE = 'FD' AND VOUCHER_TYPE='CN'  AND STATUS = 1
      AND VOUCHER_ID NOT IN ( SELECT FD_VOUCHER_ID FROM FD_RENEWAL UNION ALL SELECT FD_VOUCHER_ID FROM FD_ACCOUNT);

      SELECT ('5. Verified Invalid FD Interest Vouchers') AS MSG;
    END;
  END IF;

  -- 6. Delete (STATUS=0) FD Interest Journal Voucher entries in Voucher_Master_Trans those are not linked in FD_INTEREST_VOUCHER_ID in FD_RENEWAL
  SELECT COUNT(*) INTO RecordsCount FROM VOUCHER_MASTER_TRANS WHERE VOUCHER_SUB_TYPE = 'FD' AND VOUCHER_TYPE='JN' AND STATUS = 1
  AND VOUCHER_ID NOT IN ( SELECT FD_INTEREST_VOUCHER_ID FROM FD_RENEWAL);
  IF RecordsCount > 0 THEN
    BEGIN
      UPDATE VOUCHER_MASTER_TRANS SET STATUS=0 WHERE VOUCHER_SUB_TYPE = 'FD' AND VOUCHER_TYPE='JN' AND STATUS = 1
      AND VOUCHER_ID NOT IN ( SELECT FD_INTEREST_VOUCHER_ID FROM FD_RENEWAL);
      
	  SELECT ('6. Verified Invalid FD Interest Vouchers') AS MSG;
    END;
  END IF;
  
  -- 7. Delete (STATUS=0) FD Interest Receipt Voucher entries in Voucher_Master_Trans those are not linked in FD_INTEREST_VOUCHER_ID in FD_RENEWAL
  SELECT COUNT(*) INTO RecordsCount FROM VOUCHER_MASTER_TRANS WHERE VOUCHER_SUB_TYPE = 'FD' AND VOUCHER_TYPE='RC' AND STATUS = 1
  AND VOUCHER_ID NOT IN ( SELECT FD_INTEREST_VOUCHER_ID FROM FD_RENEWAL);
  IF RecordsCount > 0 THEN
    BEGIN
      UPDATE VOUCHER_MASTER_TRANS SET STATUS=0 WHERE VOUCHER_SUB_TYPE = 'FD' AND VOUCHER_TYPE='RC' AND STATUS = 1
      AND VOUCHER_ID NOT IN ( SELECT FD_INTEREST_VOUCHER_ID FROM FD_RENEWAL);
      
	  SELECT ('6. Verified Invalid FD Interest Vouchers') AS MSG;
    END;
  END IF;

  -- For monthly post Interest, renfnew fd can have interest value 0 ***
  -- 7. Remove FD Renew details If fd renew record contains FD_INTEREST_VOUCHER_ID = 0 (for renew, FD_INTEREST_VOUCHER_ID is mandatory)
  -- SELECT COUNT(*) INTO RecordsCount FROM FD_RENEWAL WHERE FD_TYPE = 'RN' AND FD_INTEREST_VOUCHER_ID = 0;
  -- IF RecordsCount > 0 THEN
  --  BEGIN
  --   DELETE FROM FD_RENEWAL WHERE FD_TYPE='RN' AND FD_INTEREST_VOUCHER_ID = 0;

  --    SELECT ('7. Removed Invalid FD Renew entry') AS MSG;
  --  END;
  -- END IF;
  
  -- For Invalida FD INTEREST AMOUNT (IF FD_INTEREST_VOUCHER_ID = 0 but INTEREST_AMOUNT > 0)
  -- 7. Update INTEREST_AMOUNT = 0 for all entries contains (FD_INTEREST_VOUCHER_ID = 0 AND INTEREST_AMOUNT > 0)
  SELECT COUNT(*) INTO RecordsCount FROM FD_RENEWAL WHERE (FD_INTEREST_VOUCHER_ID = 0 AND INTEREST_AMOUNT > 0);
  IF RecordsCount > 0 THEN
    BEGIN
      UPDATE FD_RENEWAL SET INTEREST_AMOUNT = 0 WHERE (FD_INTEREST_VOUCHER_ID = 0 AND INTEREST_AMOUNT > 0);
      
	  SELECT ('7. Updated Invalid FD Interest Vouchers if no receipts but INTEREST_AMOUNT > 0') AS MSG;
    END;
  END IF;
  
  -- 8. For FD Post interest : It takes previous renewal created/Renewal date as current renewal date
  -- we changed MATURITY_DATE as RENEWAL_DATE 
  -- On 18/04/2024, we modified logic for post interest will have real maturity (its renewal's maturity date)
  -- UPDATE fd_renewal SET RENEWAL_DATE = MATURITY_DATE WHERE FD_TYPE='POI' AND RENEWAL_DATE <> MATURITY_DATE;
    UPDATE FD_RENEWAL FR INNER JOIN VOUCHER_MASTER_TRANS VM ON VM.VOUCHER_ID = FR.FD_INTEREST_VOUCHER_ID
         AND FD_TYPE='POI' AND VM.VOUCHER_DATE <> FR.RENEWAL_DATE AND FR.STATUS=1
    SET FR.RENEWAL_DATE = VM.VOUCHER_DATE
    WHERE VM.VOUCHER_SUB_TYPE = 'FD' AND VM.STATUS = 1;
  
  -- 9. In old build, if FD OP deletes, ledger balance amount is not getting updated/refreshed
  -- this will sum FD OP amount based on project and FD ledgers and update to ledger balance fd ledgers op records
  UPDATE LEDGER_BALANCE LB LEFT JOIN
     (SELECT FD.PROJECT_ID, FD.LEDGER_ID, SUM(IFNULL(FD.AMOUNT,0)) OP FROM FD_ACCOUNT FD
        WHERE FD.TRANS_TYPE = 'OP' AND FD.STATUS = 1 GROUP BY FD.PROJECT_ID, FD.LEDGER_ID) AS FDOP
     ON FDOP.PROJECT_ID = LB.PROJECT_ID AND FDOP.LEDGER_ID = LB.LEDGER_ID
  SET LB.AMOUNT = IFNULL(FDOP.OP,0)
  WHERE LB.TRANS_FLAG = 'OP' AND LB.LEDGER_ID IN (SELECT LEDGER_ID FROM MASTER_LEDGER ML WHERE ML.GROUP_ID = 14);

END;

CALL VerifyInvalidFDVouchers();
