//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bosco.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLAssemblyTypeSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLAssemblyTypeSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bosco.SQL.SQLAssemblyTypeSetting", typeof(SQLAssemblyTypeSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AccountingPeriodSQL,Bosco.SQL.
        /// </summary>
        internal static string AccountingPeriod {
            get {
                return ResourceManager.GetString("AccountingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AcMePlusMigrationSQL,Bosco.SQL.
        /// </summary>
        internal static string AcMePlusMigration {
            get {
                return ResourceManager.GetString("AcMePlusMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AddressBookSQL,Bosco.SQL.
        /// </summary>
        internal static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetAMCRenewalSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetAMCRenewal {
            get {
                return ResourceManager.GetString("AssetAMCRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AMCVoucherSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetAMCVoucher {
            get {
                return ResourceManager.GetString("AssetAMCVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetCategorySQL,Bosco.SQL.
        /// </summary>
        internal static string AssetCategory {
            get {
                return ResourceManager.GetString("AssetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetClassSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetClass {
            get {
                return ResourceManager.GetString("AssetClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CustodiansSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetCustodians {
            get {
                return ResourceManager.GetString("AssetCustodians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetDepreciationSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetDepreciation {
            get {
                return ResourceManager.GetString("AssetDepreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetInwardOutwardSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetInOut {
            get {
                return ResourceManager.GetString("AssetInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetInsurancePlanSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetInsurance {
            get {
                return ResourceManager.GetString("AssetInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.InsuranceRenewalSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetInsuranceRenewal {
            get {
                return ResourceManager.GetString("AssetInsuranceRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.InsuranceSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetInsuranchVoucher {
            get {
                return ResourceManager.GetString("AssetInsuranchVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetItemSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetItem {
            get {
                return ResourceManager.GetString("AssetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetLedgerMappingSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetLedgerMapping {
            get {
                return ResourceManager.GetString("AssetLedgerMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LocationSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetLocation {
            get {
                return ResourceManager.GetString("AssetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetMappingSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetMapping {
            get {
                return ResourceManager.GetString("AssetMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetPurchaseVoucherSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetPurchaseVoucher {
            get {
                return ResourceManager.GetString("AssetPurchaseVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.InsuranceRenewSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetRenewInsurance {
            get {
                return ResourceManager.GetString("AssetRenewInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetSalesVoucherSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetSalesVoucher {
            get {
                return ResourceManager.GetString("AssetSalesVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetServiceSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetService {
            get {
                return ResourceManager.GetString("AssetService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetTransferSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetTransferVoucher {
            get {
                return ResourceManager.GetString("AssetTransferVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetUnitOfMeasureSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetUnitOfMeasure {
            get {
                return ResourceManager.GetString("AssetUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AuditTypeSQL,Bosco.SQL.
        /// </summary>
        internal static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AuditInfoSQL,Bosco.SQL.
        /// </summary>
        internal static string AuditInfo {
            get {
                return ResourceManager.GetString("AuditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AuditLockTransSQL,Bosco.SQL.
        /// </summary>
        internal static string AuditLockTrans {
            get {
                return ResourceManager.GetString("AuditLockTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BankSQL,Bosco.SQL.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BlockSQL,Bosco.SQL.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BudgetSQL,Bosco.SQL.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LedgerSQL,Bosco.SQL.
        /// </summary>
        internal static string CongregationLedgers {
            get {
                return ResourceManager.GetString("CongregationLedgers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CostCentreSQL,Bosco.SQL.
        /// </summary>
        internal static string CostCentre {
            get {
                return ResourceManager.GetString("CostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CostCentreCategorySQL,Bosco.SQL.
        /// </summary>
        internal static string CostCentreCategory {
            get {
                return ResourceManager.GetString("CostCentreCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CountrySQL,Bosco.SQL.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ReportCustomizationSQL,Bosco.SQL.
        /// </summary>
        internal static string CustomReport {
            get {
                return ResourceManager.GetString("CustomReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DashBoardSQL,Bosco.SQL.
        /// </summary>
        internal static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DeducteeTaxSQL,Bosco.SQL.
        /// </summary>
        internal static string DeducteeTax {
            get {
                return ResourceManager.GetString("DeducteeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DeducteeTypeSQL,Bosco.SQL.
        /// </summary>
        internal static string DeducteeType {
            get {
                return ResourceManager.GetString("DeducteeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DenominationSql,Bosco.SQL.
        /// </summary>
        internal static string Denomination {
            get {
                return ResourceManager.GetString("Denomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DepriciationVoucherSQL,Bosco.SQL.
        /// </summary>
        internal static string Depriciation {
            get {
                return ResourceManager.GetString("Depriciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DonorAuditorSQL,Bosco.SQL.
        /// </summary>
        internal static string DonorAuditor {
            get {
                return ResourceManager.GetString("DonorAuditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ProspectSQL,Bosco.SQL.
        /// </summary>
        internal static string DonorProspect {
            get {
                return ResourceManager.GetString("DonorProspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DonorRegistrationTypeSQL,Bosco.SQL.
        /// </summary>
        internal static string DonorRegistrationType {
            get {
                return ResourceManager.GetString("DonorRegistrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DonorTitleSQL,Bosco.SQL.
        /// </summary>
        internal static string DonorTitle {
            get {
                return ResourceManager.GetString("DonorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ExecutiveMemberSQL,Bosco.SQL.
        /// </summary>
        internal static string ExecutiveMembers {
            get {
                return ResourceManager.GetString("ExecutiveMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ExportVouchersSQL,Bosco.SQL.
        /// </summary>
        internal static string ExportVouchers {
            get {
                return ResourceManager.GetString("ExportVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.FDAccountSQL,Bosco.SQL.
        /// </summary>
        internal static string FDAccount {
            get {
                return ResourceManager.GetString("FDAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.FDRenewalSQL,Bosco.SQL.
        /// </summary>
        internal static string FDRenewal {
            get {
                return ResourceManager.GetString("FDRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.FixedDepositSQL,Bosco.SQL.
        /// </summary>
        internal static string FixedDeposit {
            get {
                return ResourceManager.GetString("FixedDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DonorFrontOfficeSQL,Bosco.SQL.
        /// </summary>
        internal static string FrontOffice {
            get {
                return ResourceManager.GetString("FrontOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.GSTClassSQL,Bosco.SQL.
        /// </summary>
        internal static string GSTDetails {
            get {
                return ResourceManager.GetString("GSTDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.HeadOfficeLedgersSQL,Bosco.SQL.
        /// </summary>
        internal static string ImportLedger {
            get {
                return ResourceManager.GetString("ImportLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ImportMasterSQL,Bosco.SQL.
        /// </summary>
        internal static string ImportMaster {
            get {
                return ResourceManager.GetString("ImportMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.InKindArticleSQL,Bosco.SQL.
        /// </summary>
        internal static string InKindArticle {
            get {
                return ResourceManager.GetString("InKindArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.InKindReceivedSQL,Bosco.SQL.
        /// </summary>
        internal static string InKindReceived {
            get {
                return ResourceManager.GetString("InKindReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.InstitutionTypeSQL,Bosco.SQL.
        /// </summary>
        internal static string InstutionType {
            get {
                return ResourceManager.GetString("InstutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LedgerSQL,Bosco.SQL.
        /// </summary>
        internal static string LedgerBank {
            get {
                return ResourceManager.GetString("LedgerBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LedgerGroupSQL,Bosco.SQL.
        /// </summary>
        internal static string LedgerGroup {
            get {
                return ResourceManager.GetString("LedgerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LedgerProfileSQL,Bosco.SQL.
        /// </summary>
        internal static string LedgerProfile {
            get {
                return ResourceManager.GetString("LedgerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LegalEntitySQL,Bosco.SQL.
        /// </summary>
        internal static string LegalEntity {
            get {
                return ResourceManager.GetString("LegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ManageSecuritySQL,Bosco.SQL.
        /// </summary>
        internal static string ManageSecurity {
            get {
                return ResourceManager.GetString("ManageSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ManufactureInfoSQL,Bosco.SQL.
        /// </summary>
        internal static string ManufactureInfo {
            get {
                return ResourceManager.GetString("ManufactureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.MappingSQL,Bosco.SQL.
        /// </summary>
        internal static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.MasterDonorReferenceSQL,Bosco.SQL.
        /// </summary>
        internal static string MasterDonorReference {
            get {
                return ResourceManager.GetString("MasterDonorReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.MasterRightsSQL,Bosco.SQL.
        /// </summary>
        internal static string MasterRights {
            get {
                return ResourceManager.GetString("MasterRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CostCentreMasterSQL,Bosco.SQL.
        /// </summary>
        internal static string MasterTransactionCostCentre {
            get {
                return ResourceManager.GetString("MasterTransactionCostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.NatureofPaymentSQL,Bosco.SQL.
        /// </summary>
        internal static string NatureofPayments {
            get {
                return ResourceManager.GetString("NatureofPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.PortalMessageSQL,Bosco.SQL.
        /// </summary>
        internal static string PortalMessage {
            get {
                return ResourceManager.GetString("PortalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ProjectSQL,Bosco.SQL.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ProjectCatogory,Bosco.SQL.
        /// </summary>
        internal static string ProjectCatogory {
            get {
                return ResourceManager.GetString("ProjectCatogory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.PurposeSQL,Bosco.SQL.
        /// </summary>
        internal static string Purposes {
            get {
                return ResourceManager.GetString("Purposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.SettingSQL,Bosco.SQL.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StateSQL,Bosco.SQL.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StatisticsTypeSQL,Bosco.SQL.
        /// </summary>
        internal static string StatisticsType {
            get {
                return ResourceManager.GetString("StatisticsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockCategorySQL,Bosco.SQL.
        /// </summary>
        internal static string StockCategory {
            get {
                return ResourceManager.GetString("StockCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockGroupSQL,Bosco.SQL.
        /// </summary>
        internal static string StockGroup {
            get {
                return ResourceManager.GetString("StockGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockItemSQL,Bosco.SQL.
        /// </summary>
        internal static string StockItem {
            get {
                return ResourceManager.GetString("StockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockItemTransferSQL,Bosco.SQL.
        /// </summary>
        internal static string StockItemTransfer {
            get {
                return ResourceManager.GetString("StockItemTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockLedgerMappingSQL,Bosco.SQL.
        /// </summary>
        internal static string StockLedgerMapping {
            get {
                return ResourceManager.GetString("StockLedgerMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockLocationSQL,Bosco.SQL.
        /// </summary>
        internal static string StockLocation {
            get {
                return ResourceManager.GetString("StockLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockPurchaseSQL,Bosco.SQL.
        /// </summary>
        internal static string StockMasterPurchase {
            get {
                return ResourceManager.GetString("StockMasterPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockSalesSQL,Bosco.SQL.
        /// </summary>
        internal static string StockMasterSales {
            get {
                return ResourceManager.GetString("StockMasterSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockPurchaseDetailSQL,Bosco.SQL.
        /// </summary>
        internal static string StockPurchaseDetail {
            get {
                return ResourceManager.GetString("StockPurchaseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockPurchaseReturnSQL,Bosco.SQL.
        /// </summary>
        internal static string StockPurchaseReturns {
            get {
                return ResourceManager.GetString("StockPurchaseReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockPurchaseSalesSQL,Bosco.SQL.
        /// </summary>
        internal static string StockPurchaseSales {
            get {
                return ResourceManager.GetString("StockPurchaseSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockSales,Bosco.SQL.
        /// </summary>
        internal static string StockSales {
            get {
                return ResourceManager.GetString("StockSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockSalesDetailSQL,Bosco.SQL.
        /// </summary>
        internal static string StockSalesDetail {
            get {
                return ResourceManager.GetString("StockSalesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockUnitofMeasureSQL,Bosco.SQL.
        /// </summary>
        internal static string StockUnitofMeasure {
            get {
                return ResourceManager.GetString("StockUnitofMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.StockBalanceSQL,Bosco.SQL.
        /// </summary>
        internal static string StockUpdation {
            get {
                return ResourceManager.GetString("StockUpdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.SubBranchSQL,Bosco.SQL.
        /// </summary>
        internal static string SubBranchList {
            get {
                return ResourceManager.GetString("SubBranchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.SubLedgerSQL,Bosco.SQL.
        /// </summary>
        internal static string SubLedger {
            get {
                return ResourceManager.GetString("SubLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TallyMigrationSQL,Bosco.SQL.
        /// </summary>
        internal static string TallyExport {
            get {
                return ResourceManager.GetString("TallyExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TallyMigrationSQL,Bosco.SQL.
        /// </summary>
        internal static string TallyMigration {
            get {
                return ResourceManager.GetString("TallyMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSBookingSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSBooking {
            get {
                return ResourceManager.GetString("TDSBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSBookingDetailSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSBookingDetail {
            get {
                return ResourceManager.GetString("TDSBookingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSCompanyDeductors,Bosco.SQL.
        /// </summary>
        internal static string TDSCompanyDeductor {
            get {
                return ResourceManager.GetString("TDSCompanyDeductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSDeductionSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSDeduction {
            get {
                return ResourceManager.GetString("TDSDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSDeductionDetailSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSDeductionDetail {
            get {
                return ResourceManager.GetString("TDSDeductionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.PartyPaymentSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSPartyPayment {
            get {
                return ResourceManager.GetString("TDSPartyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.PartyPaymentDetailSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSPartyPaymentDetail {
            get {
                return ResourceManager.GetString("TDSPartyPaymentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSPaymentDetailSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSPayemtDetail {
            get {
                return ResourceManager.GetString("TDSPayemtDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSPaymentSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSPayment {
            get {
                return ResourceManager.GetString("TDSPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSSectionSQL,Bosco.SQL.
        /// </summary>
        internal static string TDSSection {
            get {
                return ResourceManager.GetString("TDSSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BalanceSQL,Bosco.SQL.
        /// </summary>
        internal static string TransBalance {
            get {
                return ResourceManager.GetString("TransBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.UISettingSQL,Bosco.SQL.
        /// </summary>
        internal static string UISetting {
            get {
                return ResourceManager.GetString("UISetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.UserSQL,Bosco.SQL.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.UserRightsSQL,Bosco.SQL.
        /// </summary>
        internal static string UserRights {
            get {
                return ResourceManager.GetString("UserRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.UserRoleSQL,Bosco.SQL.
        /// </summary>
        internal static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.VendorInfoSQL,Bosco.SQL.
        /// </summary>
        internal static string VendorInfo {
            get {
                return ResourceManager.GetString("VendorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.VoucherSQL,Bosco.SQL.
        /// </summary>
        internal static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.VoucherDepreciationSQL,Bosco.SQL.
        /// </summary>
        internal static string VoucherDepreciation {
            get {
                return ResourceManager.GetString("VoucherDepreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.VoucherMasterSQL,Bosco.SQL.
        /// </summary>
        internal static string VoucherMaster {
            get {
                return ResourceManager.GetString("VoucherMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.VoucherTransSQL,Bosco.SQL.
        /// </summary>
        internal static string VoucherTransDetails {
            get {
                return ResourceManager.GetString("VoucherTransDetails", resourceCulture);
            }
        }
    }
}
