//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcMEService.SSPAcmeIntegration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SSPAcmeIntegration.SSPAcmeIntegrationSoap")]
    public interface SSPAcmeIntegrationSoap {
        
        // CODEGEN: Generating message contract since message GetMastersRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMasters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AcMEService.SSPAcmeIntegration.GetMastersResponse GetMasters(AcMEService.SSPAcmeIntegration.GetMastersRequest request);
        
        // CODEGEN: Generating message contract since message GetTrasnsactionDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrasnsactionDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AcMEService.SSPAcmeIntegration.GetTrasnsactionDetailsResponse GetTrasnsactionDetails(AcMEService.SSPAcmeIntegration.GetTrasnsactionDetailsRequest request);
        
        // CODEGEN: Generating message contract since message UpdateTransactionDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTransactionDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AcMEService.SSPAcmeIntegration.UpdateTransactionDetailsResponse UpdateTransactionDetails(AcMEService.SSPAcmeIntegration.UpdateTransactionDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMasters", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMastersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ManagementCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MasterDetails;
        
        public GetMastersRequest() {
        }
        
        public GetMastersRequest(AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader, string ManagementCode, string MasterDetails) {
            this.AuthHeader = AuthHeader;
            this.ManagementCode = ManagementCode;
            this.MasterDetails = MasterDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMastersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMastersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetMastersResult;
        
        public GetMastersResponse() {
        }
        
        public GetMastersResponse(string GetMastersResult) {
            this.GetMastersResult = GetMastersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrasnsactionDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrasnsactionDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ManagementCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string DateTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string MasterDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Projects;
        
        public GetTrasnsactionDetailsRequest() {
        }
        
        public GetTrasnsactionDetailsRequest(AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader, string ManagementCode, string DateFrom, string DateTo, string MasterDetails, string Projects) {
            this.AuthHeader = AuthHeader;
            this.ManagementCode = ManagementCode;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
            this.MasterDetails = MasterDetails;
            this.Projects = Projects;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrasnsactionDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrasnsactionDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetTrasnsactionDetailsResult;
        
        public GetTrasnsactionDetailsResponse() {
        }
        
        public GetTrasnsactionDetailsResponse(string GetTrasnsactionDetailsResult) {
            this.GetTrasnsactionDetailsResult = GetTrasnsactionDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTransactionDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateTransactionDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ManagementCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string TransactionDetails;
        
        public UpdateTransactionDetailsRequest() {
        }
        
        public UpdateTransactionDetailsRequest(AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader, string ManagementCode, string TransactionDetails) {
            this.AuthHeader = AuthHeader;
            this.ManagementCode = ManagementCode;
            this.TransactionDetails = TransactionDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTransactionDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateTransactionDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateTransactionDetailsResult;
        
        public UpdateTransactionDetailsResponse() {
        }
        
        public UpdateTransactionDetailsResponse(string UpdateTransactionDetailsResult) {
            this.UpdateTransactionDetailsResult = UpdateTransactionDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SSPAcmeIntegrationSoapChannel : AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSPAcmeIntegrationSoapClient : System.ServiceModel.ClientBase<AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap>, AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap {
        
        public SSPAcmeIntegrationSoapClient() {
        }
        
        public SSPAcmeIntegrationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSPAcmeIntegrationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSPAcmeIntegrationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSPAcmeIntegrationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AcMEService.SSPAcmeIntegration.GetMastersResponse AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap.GetMasters(AcMEService.SSPAcmeIntegration.GetMastersRequest request) {
            return base.Channel.GetMasters(request);
        }
        
        public string GetMasters(AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader, string ManagementCode, string MasterDetails) {
            AcMEService.SSPAcmeIntegration.GetMastersRequest inValue = new AcMEService.SSPAcmeIntegration.GetMastersRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ManagementCode = ManagementCode;
            inValue.MasterDetails = MasterDetails;
            AcMEService.SSPAcmeIntegration.GetMastersResponse retVal = ((AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap)(this)).GetMasters(inValue);
            return retVal.GetMastersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AcMEService.SSPAcmeIntegration.GetTrasnsactionDetailsResponse AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap.GetTrasnsactionDetails(AcMEService.SSPAcmeIntegration.GetTrasnsactionDetailsRequest request) {
            return base.Channel.GetTrasnsactionDetails(request);
        }
        
        public string GetTrasnsactionDetails(AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader, string ManagementCode, string DateFrom, string DateTo, string MasterDetails, string Projects) {
            AcMEService.SSPAcmeIntegration.GetTrasnsactionDetailsRequest inValue = new AcMEService.SSPAcmeIntegration.GetTrasnsactionDetailsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ManagementCode = ManagementCode;
            inValue.DateFrom = DateFrom;
            inValue.DateTo = DateTo;
            inValue.MasterDetails = MasterDetails;
            inValue.Projects = Projects;
            AcMEService.SSPAcmeIntegration.GetTrasnsactionDetailsResponse retVal = ((AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap)(this)).GetTrasnsactionDetails(inValue);
            return retVal.GetTrasnsactionDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AcMEService.SSPAcmeIntegration.UpdateTransactionDetailsResponse AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap.UpdateTransactionDetails(AcMEService.SSPAcmeIntegration.UpdateTransactionDetailsRequest request) {
            return base.Channel.UpdateTransactionDetails(request);
        }
        
        public string UpdateTransactionDetails(AcMEService.SSPAcmeIntegration.AuthHeader AuthHeader, string ManagementCode, string TransactionDetails) {
            AcMEService.SSPAcmeIntegration.UpdateTransactionDetailsRequest inValue = new AcMEService.SSPAcmeIntegration.UpdateTransactionDetailsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ManagementCode = ManagementCode;
            inValue.TransactionDetails = TransactionDetails;
            AcMEService.SSPAcmeIntegration.UpdateTransactionDetailsResponse retVal = ((AcMEService.SSPAcmeIntegration.SSPAcmeIntegrationSoap)(this)).UpdateTransactionDetails(inValue);
            return retVal.UpdateTransactionDetailsResult;
        }
    }
}
