//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLAssemblyTypeSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLAssemblyTypeSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Payroll.SQL.SQLAssemblyTypeSetting", typeof(SQLAssemblyTypeSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.AddressBookSQL,Payroll.SQL.
        /// </summary>
        internal static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.AuditInfoSQL,Payroll.SQL.
        /// </summary>
        internal static string AuditInfo {
            get {
                return ResourceManager.GetString("AuditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.BankSQL,Payroll.SQL.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.CostCentreSQL,Payroll.SQL.
        /// </summary>
        internal static string CostCentre {
            get {
                return ResourceManager.GetString("CostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.CountrySQL,Payroll.SQL.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.DonorAuditorSQL,Payroll.SQL.
        /// </summary>
        internal static string DonorAuditor {
            get {
                return ResourceManager.GetString("DonorAuditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.ExecutiveMemberSQL,Payroll.SQL.
        /// </summary>
        internal static string ExecutiveMembers {
            get {
                return ResourceManager.GetString("ExecutiveMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.InKindArticleSQL,Payroll.SQL.
        /// </summary>
        internal static string InKindArticle {
            get {
                return ResourceManager.GetString("InKindArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.LedgerSQL,Payroll.SQL.
        /// </summary>
        internal static string LedgerBank {
            get {
                return ResourceManager.GetString("LedgerBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.LedgerGroupSQL,Payroll.SQL.
        /// </summary>
        internal static string LedgerGroup {
            get {
                return ResourceManager.GetString("LedgerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.ManageSecuritySQL,Payroll.SQL.
        /// </summary>
        internal static string ManageSecurity {
            get {
                return ResourceManager.GetString("ManageSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.MasterRightsSQL,Payroll.SQL.
        /// </summary>
        internal static string MasterRights {
            get {
                return ResourceManager.GetString("MasterRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.ProjectSQL,Payroll.SQL.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.ProjectCatogory,Payroll.SQL.
        /// </summary>
        internal static string ProjectCatogory {
            get {
                return ResourceManager.GetString("ProjectCatogory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.PurposeSQL,Payroll.SQL.
        /// </summary>
        internal static string Purposes {
            get {
                return ResourceManager.GetString("Purposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.SettingSQL,Payroll.SQL.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.UISettingSQL,Payroll.SQL.
        /// </summary>
        internal static string UISetting {
            get {
                return ResourceManager.GetString("UISetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.UserSQL,Payroll.SQL.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.UserRightsSQL,Payroll.SQL.
        /// </summary>
        internal static string UserRights {
            get {
                return ResourceManager.GetString("UserRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.UserRoleSQL,Payroll.SQL.
        /// </summary>
        internal static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.SQL.VoucherSQL,Payroll.SQL.
        /// </summary>
        internal static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
    }
}
