//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcMEDSync.DataSyncService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataSyncService.IDataSynchronizer")]
    public interface IDataSynchronizer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/GetMasters", ReplyAction="http://tempuri.org/IDataSynchronizer/GetMastersResponse")]
        System.Data.DataSet GetMasters(string headOfficeCode, string branchOfficeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/WriteMastersToXML", ReplyAction="http://tempuri.org/IDataSynchronizer/WriteMastersToXMLResponse")]
        bool WriteMastersToXML(string headOfficeCode, string branchOfficeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/GetHeadOfficeMailAddress", ReplyAction="http://tempuri.org/IDataSynchronizer/GetHeadOfficeMailAddressResponse")]
        string GetHeadOfficeMailAddress(string headOfficeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/GetBranchMailAddress", ReplyAction="http://tempuri.org/IDataSynchronizer/GetBranchMailAddressResponse")]
        string GetBranchMailAddress(string branchOfficeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/GetOfficeMailAddress", ReplyAction="http://tempuri.org/IDataSynchronizer/GetOfficeMailAddressResponse")]
        string GetOfficeMailAddress(string headOfficeCode, string branchOfficeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/FetchMailContent", ReplyAction="http://tempuri.org/IDataSynchronizer/FetchMailContentResponse")]
        System.Data.DataTable FetchMailContent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/UploadBranchVouchers", ReplyAction="http://tempuri.org/IDataSynchronizer/UploadBranchVouchersResponse")]
        bool UploadBranchVouchers(System.Data.DataSet dsVouchers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/UploadVoucherCompressedDataset", ReplyAction="http://tempuri.org/IDataSynchronizer/UploadVoucherCompressedDatasetResponse")]
        bool UploadVoucherCompressedDataset(byte[] Vouchers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataSynchronizerChannel : AcMEDSync.DataSyncService.IDataSynchronizer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataSynchronizerClient : System.ServiceModel.ClientBase<AcMEDSync.DataSyncService.IDataSynchronizer>, AcMEDSync.DataSyncService.IDataSynchronizer {
        
        public DataSynchronizerClient() {
        }
        
        public DataSynchronizerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataSynchronizerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataSynchronizerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataSynchronizerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetMasters(string headOfficeCode, string branchOfficeCode) {
            return base.Channel.GetMasters(headOfficeCode, branchOfficeCode);
        }
        
        public bool WriteMastersToXML(string headOfficeCode, string branchOfficeCode) {
            return base.Channel.WriteMastersToXML(headOfficeCode, branchOfficeCode);
        }
        
        public string GetHeadOfficeMailAddress(string headOfficeCode) {
            return base.Channel.GetHeadOfficeMailAddress(headOfficeCode);
        }
        
        public string GetBranchMailAddress(string branchOfficeCode) {
            return base.Channel.GetBranchMailAddress(branchOfficeCode);
        }
        
        public string GetOfficeMailAddress(string headOfficeCode, string branchOfficeCode) {
            return base.Channel.GetOfficeMailAddress(headOfficeCode, branchOfficeCode);
        }
        
        public System.Data.DataTable FetchMailContent() {
            return base.Channel.FetchMailContent();
        }
        
        public bool UploadBranchVouchers(System.Data.DataSet dsVouchers) {
            return base.Channel.UploadBranchVouchers(dsVouchers);
        }
        
        public bool UploadVoucherCompressedDataset(byte[] Vouchers) {
            return base.Channel.UploadVoucherCompressedDataset(Vouchers);
        }
    }
}
